<?php

namespace App\Core\Base;

use App\Core\Support\Meta\Meta;
use Illuminate\Database\Eloquent\Model as Eloquent;
use Illuminate\Support\Str;

/**
 * Class Model.
 */
abstract class Model extends Eloquent
{
    /**
     * @var bool
     */
    public $useSlug = false;
    public $uniqueId = 'unique_id';

    protected static function boot()
    {
        parent::boot();
    }

    /**
     * @param string $key
     * @return Meta|mixed
     */
    public function __get($key)
    {
        if ($key == 'meta') {
            $file = $this->getName();

            return $this->getMetaRelation($file);
        }

        return parent::__get($key); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $method
     * @param array $parameters
     * @return Meta|mixed
     */
    public function __call($method, $parameters)
    {
        if ($method == 'find') {
            $this->finder(...$parameters);
        }
        if ($method == 'meta') {
            $file = $this->getName();

            return $this->getMetaRelation($file);
        }

        return parent::__call($method, $parameters);
    }

    /**
     * Handle dynamic static method calls into the method.
     *
     * @param  string $method
     * @param  array $parameters
     * @return mixed
     */
    public static function __callStatic($method, $parameters)
    {
        if ($method == 'find') {
            return (new static)->finder(...$parameters);
        }

        return (new static)->$method(...$parameters);
    }

    /**
     * method find rewrite.
     *
     * @param $id
     * @param array $columns
     * @return \Illuminate\Database\Eloquent\Collection|Eloquent|null|static
     * @throws \Exception
     */
    public function finder($id, $columns = ['*'])
    {
        $newQuery = $this->newQuery();
        if (is_array($id)) {
            return $newQuery->findMany($id, $columns);
        }

        if (is_numeric($id)) {
            $newQuery->where($this->getQualifiedKeyName(), '=', $id);

            return $newQuery->first($columns);
        } else {
            if ($this->useSlug) {
                if (isset($this->slug) || ! empty($this->slug)) {
                    $this->primaryKey = 'slug';

                    return $newQuery->where($this->getQualifiedKeyName(), '=', $id)->first($columns);
                } else {
                    throw new \Exception('Please specify slug field in the model', 404);
                }
            }
            $this->primaryKey = $this->uniqueId;
            $newQuery = $this->newQuery();
            $newQuery->where($this->getQualifiedKeyName(), '=', $id);

            return $newQuery->first($columns);
        }
    }

    /**
     * @return string
     */
    private function getName()
    {
        $path = explode('\\', get_class($this));

        return Str::snake(array_pop($path));
    }

    /**
     * @param $file
     * @return Meta
     */
    private function getMetaRelation($file)
    {
        $meta = new Meta();
        $meta->setTable($file.'_meta');

        return $meta;
    }
}
