<?php

return [
    'attribute_group',
    'attribute_group_description',
    'banner',
    'campaign',
    'cart',
    'coupon',
    'folder',
    'layout',
    'mail',
    'media',
    'message',
    'orders',
    'participant',
    'permission',
    'product',
    'product_review',
    'promocode',
    'returns',
    'role',
    'static_pages',
    'subscribers',
    'thread',
    'transaction',
];
